---

- name: Install all security, critical, and rollup updates 
  hosts: windows
  tasks:
    - name: Running Windows Update
      win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups', 'Updates', 'DefinitionUpdates']
      register: result

    
    # reboot only if required
    - win_reboot:
      when: result.reboot_required
